disp('-------------------------------------------------------------------');
disp('                          IQClab v3.04                             ');
disp('-------------------------------------------------------------------');
disp('Thanks for considering IQClab, your gateway for robustness analysis');
disp('and control. Please visit www.iqclab.eu for the user manual, demos,');
disp('and furter information.                                            ');
disp('                                                                   ');
disp('This is copyrighted material owned by Novantec B.V.                ');
disp('                                                                   ');
disp('By installing and using IQClab you accept the Creative Commons     ');
disp('Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0) license ');
disp('terms and conditions. For further details (and the legal code      ');
disp('please visit:                                                      ');
disp('https://creativecommons.org/licenses/by-nd/4.0/                    ');
disp('https://creativecommons.org/licenses/by-nd/4.0/legalcode.en        ');
disp('-------------------------------------------------------------------');